[package]
name = "SimpleJsonWebRust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rocket = "0.4.6"
rocket_contrib = { version = "0.4.6", features = ["json"] }
serde = { version = "1.0.117", features = ["derive"] }
